# Generated by Django 4.2.1 on 2023-05-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('Hip Hop', 'Hip Hop'), ('Sythétic Pop', 'Synth Pop'), ('Alternative Rock', 'Alternative Rock')], default='HH', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('Records', 'Records'), ('Clothings', 'Clothing'), ('Poster', 'Poster'), ('Miscellaneous', 'Miscellaneous')], default='M', max_length=50),
        ),
    ]
